### ISSUE TITLE
no such file or directory: termnames.json

### ISSUE THREAD

**Issue by catgoose** [aaditeynair/termnames.nvim#1]
Upon executing TermOpen, I receive the error:

```
Error executing Lua callback: .../share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:32: Vim:Error executing Lua callback: ....local/share/nvim/lazy/plenary.nvim/lua/ple
nary/path.lua:738: ENOENT: no such file or directory: /home/zzz/.local/share/nvim/termnames.json
```

Using the following table to load plugin in lazy:

```lua
{
  "aaditeynair/termnames.nvim",
  cmd = {
	  "TermOpen",
	  "TermRename",
	  "TermClose",
  },
  dependencies = {
	  "nvim-lua/plenary.nvim",
	  "famiu/bufdelete.nvim",
  },
},
```

**Comment by aaditeynair** [comment]
It was a silly mistake on my part. I left out quite an important check in the code. It should be fixed now. Let me know if it works!

**Comment by catgoose** [comment]
I still receive the same error.  Does that file need to be created?

edit: I guess I didn't update for the new commit.  I no longer receive error.
